[general]
  import = ["alacritty-colors.conf"]


[window]
  opacity = 0.90
  blur = true

[font]
  normal = { family = "JetBrainsMono NF", style = "Regular" }
  bold = { family = "JetBrainsMono NF", style = "Bold" }
  italic = {family = "JetBrainsMono NF", style = "Italic" }
  size = 12
  builtin_box_drawing = true
